All but one tests pass after renaming.
The one test failure also fails on connectrpc.com/connect:

2025/09/15 11:07:52 http: TLS handshake error from 127.0.0.1:37140: read tcp 127.0.0.1:40005->127.0.0.1:37140: use of closed network connection
2025/09/15 11:07:52 http: TLS handshake error from 127.0.0.1:37152: read tcp 127.0.0.1:40005->127.0.0.1:37152: use of closed network connection
--- FAIL: TestClientDeadlineHandling (0.10s)
    --- FAIL: TestClientDeadlineHandling/read-write (4.97s)
        client_ext_test.go:773:
            assertion:  assert.Equal
            got:        unavailable
            want:       deadline_exceeded

        client_ext_test.go:783: actual receive error from /connect.ping.v1.PingService/Sum: unavailable: io: read/write on closed pipe
            &connect.Error{code:0xe, err:(*errors.errorString)(0x11b1580), details:[]*connect.ErrorDetail(nil), meta:http.Header(nil), wireErr:false}
              caused by: &errors.errorString{s:"io: read/write on closed pipe"}
        client_ext_test.go:649: Issued 146743 RPCs.